apiVersion: "v1"
kind: "Secret"
metadata:
  name: "my-database-secret"
stringData:
  user: "dev"
  password: "secret"
  
  
  
  
  
  metatdata
  name = referenced (name is provided as an env variable DB_USERNAME which gets the valie from: the "key" in deployment.yml under  
            valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   
                   
 these need to be match what is passed into the command to start a new application                  